server:
#  tomcat:
#    accept-count: 500
##    max-keep-alive-requests: -1
##    max-connections: 30000 # default 8192
##    connection-timeout: # default 60000 ms
#    threads:
#      max: 200 # default 200 / thread 경합..? 주의
#      min-spare: 200

  port: 8080

spring:
  application:
    name: api-server

  threads:
    virtual:
      enabled: true
#      enabled: false

servers: # 타 서버들의 정보 기록
  consumer: localhost:8082
  target: # 테스트용 사용자 서버(tes 24)
    url: 70.12.247.125:8080/tes24
    traffic-capacity: 200

kafka:
  topic-names:
    enter: test