server:
#  tomcat:
#    accept-count: 500
##    max-keep-alive-requests: -1
##    max-connections: 30000 # default 8192
##    connection-timeout: # default 60000 ms
#    threads:
#      max: 200 # default 200 / thread 경합..? 주의
#      min-spare: 200

  port: 8080

spring:
  application:
    name: api-server

  threads:
    virtual:
      enabled: true
#      enabled: false

  data:
    mongodb:
#      host: localhost
#      port: 27017
#      authentication-database: admin
#      username: test
#      password: 1234
#      database: test
      uri: mongodb://localhost:27017/test

servers: # 타 서버들의 정보 기록
  consumer: localhost:8082
  target: # 테스트용 사용자 서버(tes 24)
    url: http://localhost:8082/consume/test # 대기열 적용 대상 api url

kafka:
  broker: localhost:9092
  topic-names:
    enter: test