server:
  port: 8080

spring:
  application:
    name: api-server

servers: # 타 서버들의 정보 기록
  producer: 70.12.247.254:8081
  consumer: 70.12.247.254:8082
  target: # 테스트용 사용자 서버(tes 24)
    url: 70.12.247.125:8080/tes24
    traffic-capacity: 200