name: qqueueing
services:
  qqueueing-main:
    build:
      context: .
      dockerfile: build/main/Dockerfile
    image: qqueueing-backend
    networks:
      - qqueueing-network
  qqueueing-consumer:
    build: ./build/main
  qqueueing-frontend:
    build: ./build/main
  qqueueing-producer:
    build: ./build/main
  qqueueing-mysql:
    build: ./build/main
  qqueueing-kafka:
    build: ./build/main


volumes: { }

networks:
  qqueueing-network: {}

